### PR TITLE
Add more tests

### PR DESCRIPTION
**Pull request by dwaynebailey**
Broken ones are commented out as needed.

I spent a little time trying to fix some.

But tab indents? Right good luck with that one I couldn't get vim to handle them as I needed and yet still do the right thing on other python code.  You might consider adding the needed vim configs at the bottom of the files in question if you want to change the world with tabs.

### CODE REVIEW

**Comment by jleclanche** [comment]
I won't be merging this PR as is as I don't like committing commented out code, but I'll be using it as a reference to fix the broken behaviour and add the tests standalone. Thanks, good catches.

There's some behavioural concerns I raised which also need to be addressed.

**Comment by mgood** [comment]
The Java documentation is a great resource. It contains a detailed description of the parsing and serializing rules, including answers to your questions about handling lines with just whitespace and lines with just a key:
http://docs.oracle.com/javase/7/docs/api/java/util/Properties.html#load(java.io.Reader)

Also most Python test runners have a way to mark tests that are known to fail, such as "xfail" in ph.test:
https://pytest.org/latest/skipping.html#mark-a-test-function-as-expected-to-fail

**Comment by jleclanche** [comment]
@mgood Thanks for the link, added the tests mentioned there.

And yes I know about xfail, but I like being able to also just run `./test_main.py` without pytest :)

**Comment by jleclanche** [comment]
Closing this, committed most of it in different forms.

The only thing remaining is testing and fixing unicode escapes.

**Pull request closed without merging**
