### PR TITLE
1 fix, couple additions

### PR DESCRIPTION
**Pull request by Leibniz137**
- fix bug in __str__ implementation
- make Properties a collections.abc.MutableMapping instance
- implement `python setup.py test`
- use pytest as test runner/framework
- implement save method

### CODE REVIEW

**Comment by jleclanche** [comment]
This looks great. I'll merge it soon.

**Comment by jleclanche** [comment]
Your `author` and `committer` have a mismatch in name and email, could you let me know which one it is you want to use?

**Comment by Leibniz137** [comment]
Please use the author (ie the account I'm using to make this comment)

thanks!

**Comment by jleclanche** [comment]
Rebased, fixed and landed. I also added my usual pattern for tests and setup.

If you have more PRs coming, let me know, otherwise I'll probably do a 1.0 release.

**Pull request closed without merging**
