### PR TITLE
Updating Property node instead of append new if key already exists

### PR DESCRIPTION
**Pull request by lifchicker**
In case of setting property which originally was in property file, Property node will be replaced with new value.

### CODE REVIEW

**Comment by jleclanche** [comment]
Could you add a test for this please? It'll clarify what the issue is, too.

**Comment by lifchicker** [comment]
Ok. I'll try to do it tomorrow. Are there any ways how to load properties from string instead of a file? (Properties.load() for string).

**Comment by jleclanche** [comment]
`load()` takes any readable stream, so you can use `io.StringIO`.

**Comment by lifchicker** [comment]
You can try to run this test for previous version (without my changes). This test will fail, because str(props) will contain two entries

> key = value
> key = another_value

instead of only one

> key = another_value

**Comment by jleclanche** [comment]
Looks good.

Can you squash the two commits please, and while you're at it [respect the CONTRIBUTING.md guidelines on commit messages](https://github.com/translate/python-jproperties/blob/master/CONTRIBUTING.md) ;)

**Comment by lifchicker** [comment]
Better?

**Comment by jleclanche** [comment]
Yep. I'll test it tomorrow but lgtm.

**Pull request closed without merging**
